ODYSSEY(1) "github.com/paulchambaz/odyssey" "General Commands Manual"

# NAME

*odyssey* - Simple iliad terminal client

# SYNOPSIS

*odyssey* [OPTIONS]

# DESCRIPTION


# OPTIONS

*-h*, *--help*
	Print help

*--version*
	Print version

# CONFIGURATION

# AUTHORS

This program was written by Paul Chambaz in 2026. It is licensed under the
GPLv3, for more information, please read the *LICENSE* file.
